[config]
schemaVersion = "0.0.1"

[package]
namespace = "hermesdj"
name = "VRising Server WebHooks Plugin"
versionNumber = "1.0.0"
description = "Server WebHooks plugin used to subscribe to VRising Events"
websiteUrl = "https://github.com/hermesdj/VRisingApiWebHooks"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
jays.VRisingServerApiPlugin = "0.1.5"
jays.VRisingServerEvents = "0.1.0"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]